### ISSUE TITLE
To many exception when All Exceptions breakpoint is active.

### ISSUE THREAD

**Issue by 2shrestha22** [caseycrogers/flutter_gutter#3]
Previously you were checking if a widget is flex or not but after dynamic check gutter gives too many exceptions. Is there any reason for dynamic checking?

The change that is throwing error.
https://github.com/caseycrogers/flutter_gutter/blame/4c8eacff77d8726b69e9782a1adea0d10d5a2860/lib/src/gap.dart#L46-L52

**Comment by caseycrogers** [comment]
Hello, I made the change in order to support widgets that were provided by other packages (namely `BoxyRow` and `BoxyColumn`).

Here's a Flutter issue where I discuss the need and some potential solutions that Flutter could implement to avoid the dynamic check:
https://github.com/flutter/flutter/issues/133394

How about, in the meantime, I include a static bool flag that you can set to turn on or off the dynamic checking behavior? If off it'll behave just like it used to?

**Comment by 2shrestha22** [comment]
That seems like a good idea. And I think that the gutter has `gap` as a dependency but it has never been used.

**Comment by caseycrogers** [comment]
Oh man good catch, I was testing migrating to using gap internally but rolled it back, I guess not cleanly. 

Expect a new release tonight or tomorrow with these two fixes.

**Comment by 2shrestha22** [comment]
Thanks, I am ready to upgrade.

**Comment by caseycrogers** [comment]
I just put out an update that should resolve these. Let me know if you have any issues with it or further feature requests!
